[package]
name = "nu_plugin_pg"
version = "0.1.0"
edition = "2021"

[dependencies]
nu-plugin = "0.96.1"
nu-protocol = { version = "0.96.1", features = ["plugin"] }
postgres = "0.19.8"
rustls = "0.23.12"
tokio = "1.39.2"
tokio-postgres-rustls = "0.12.0"
webpki-roots = "0.26.3"
